Run this at the beginning so you can see the last one:

```
rm test.log
touch test.log
tailf test.log
```

```{r setup}
library(knitrProgressBar)
arduously_long_nchar <- function(input_var, .pb=NULL) {
  
  if ((!is.null(.pb)) && inherits(.pb, "Progress") && (.pb$i < .pb$n)) .pb$tick()$print()
  
  Sys.sleep(0.5)
  
  nchar(input_var)
  
}
```

## Normal Progress Bar

Will show up in the output document, but not in a terminal running `rmarkdown::render`.

```{r test_pb}
pb <- progress_estimated(length(letters))

purrr::map_int(letters, arduously_long_nchar, .pb = pb)
```

## Using stderr()

This one will show up in the terminal when running `rmarkdown::render`.

```{r test_pb_stderr}
pb <- progress_estimated(length(letters), write_location = stderr())

purrr::map_int(letters, arduously_long_nchar, .pb = pb)
```

## Using a file

This one will instead write to a file, and can be watched by `tailf` for example
in a linux-alike.

```{r test_pb_file}
pb <- progress_estimated(length(letters), write_location = "test.log")

purrr::map_int(letters, arduously_long_nchar, .pb = pb)
```

## No Progress Bar

```{r test_pb_null}
pb <- progress_estimated(length(letters), write_location = NULL)

purrr::map_int(letters, arduously_long_nchar, .pb = pb)
```
